const CELL_STATUSES = {
	EMPTY: 'EMPTY',
	DISABLE: 'DISABLE',
	SHIP: 'SHIP',
	HIT: 'HIT',
	MISS: 'MISS',
	SUNK: 'SUNK',
	WAVE: 'WAVE',
	HOVER: 'HOVER',
	HAS_SHIP: 'HAS_SHIP',
};

export default CELL_STATUSES;
